[env]
TERM = "xterm-256color"

[window]
opacity = 0.7

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font" 
style = "Bold"                

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Medium"

[font.italic]
family = "FiraCode Nerd Font"
style = "Medium"                

[font.normal]
family = "FiraCode Nerd Font"
style = "SemiBold"                


[general]
import = [
  "./catppuccin-mocha.toml"
]
